"""Seed >= 2 realistic, complete example runs into the `runs` table.

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run) but are coherent, realistic end-to-end traces of
exactly what the graph produces: sub-questions, per-source findings, a
cited draft, a critique, a human decision, and a finalized report. They
exist so the "Run History / Example Analyses" page has real content to
show a visitor before they run anything themselves.

Run with:
    python -m scripts.seed_examples
"""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone

from app.db.models import Run
from app.db.session import SessionLocal


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base_time: datetime, node: str, minutes: float, summary: str) -> dict:
    return {
        "node": node,
        "timestamp": _iso(base_time + timedelta(minutes=minutes)),
        "summary": summary,
    }


def build_renewable_energy_run() -> Run:
    run_id = str(uuid.uuid4())
    t0 = datetime.now(timezone.utc) - timedelta(days=3, hours=2)
    question = (
        "What are the main renewable energy sources, and how has their cost "
        "and adoption changed over the last two decades?"
    )
    sub_questions = [
        "What are the primary categories of renewable energy and how does each generate electricity?",
        "How has the cost of solar and wind power changed since the early 2000s?",
        "What policy mechanisms have driven renewable energy adoption globally?",
        "What are the main challenges that still limit renewable energy adoption?",
    ]

    findings = [
        {
            "source_id": "S1", "sub_question": sub_questions[0], "source_type": "kb",
            "title": "Defining Renewable Energy", "url_or_doc_id": "re-001",
            "synthesis": (
                "Renewable energy is generated from naturally replenishing sources -- "
                "sunlight, wind, moving water, geothermal heat, and biomass -- that are "
                "not depleted on human timescales [S1]. The main categories are solar "
                "photovoltaics, wind turbines, hydropower, geothermal plants, and "
                "biomass/bioenergy conversion, each converting a different natural "
                "energy flow into electricity or fuel [S1][S2][S3][S4]."
            ),
        },
        {
            "source_id": "S2", "sub_question": sub_questions[0], "source_type": "kb",
            "title": "Early History: Wind and Water Power", "url_or_doc_id": "re-002",
            "synthesis": (
                "Renewable energy is generated from naturally replenishing sources -- "
                "sunlight, wind, moving water, geothermal heat, and biomass -- that are "
                "not depleted on human timescales [S1]. The main categories are solar "
                "photovoltaics, wind turbines, hydropower, geothermal plants, and "
                "biomass/bioenergy conversion, each converting a different natural "
                "energy flow into electricity or fuel [S1][S2][S3][S4]."
            ),
        },
        {
            "source_id": "S3", "sub_question": sub_questions[1], "source_type": "kb",
            "title": "Solar Photovoltaics: From Lab to Grid Scale", "url_or_doc_id": "re-003",
            "synthesis": (
                "Solar photovoltaic costs fell roughly 90% between 2010 and 2020 as "
                "manufacturing scaled globally, making utility-scale solar one of the "
                "cheapest sources of new electricity generation in much of the world by "
                "the early 2020s [S3]. Modern commercial panels convert 18-22% of "
                "incident sunlight to electricity, up from single-digit efficiencies in "
                "early spacecraft-era cells [S3]. Wind turbine capacity has similarly "
                "grown from tens of kilowatts in the 1980s to over 12-15 megawatts per "
                "offshore unit today, with wind now among the fastest-growing "
                "electricity sources worldwide [S4][S6]."
            ),
        },
        {
            "source_id": "S4", "sub_question": sub_questions[1], "source_type": "kb",
            "title": "Modern Wind Power", "url_or_doc_id": "re-004",
            "synthesis": (
                "Solar photovoltaic costs fell roughly 90% between 2010 and 2020 as "
                "manufacturing scaled globally, making utility-scale solar one of the "
                "cheapest sources of new electricity generation in much of the world by "
                "the early 2020s [S3]. Modern commercial panels convert 18-22% of "
                "incident sunlight to electricity, up from single-digit efficiencies in "
                "early spacecraft-era cells [S3]. Wind turbine capacity has similarly "
                "grown from tens of kilowatts in the 1980s to over 12-15 megawatts per "
                "offshore unit today, with wind now among the fastest-growing "
                "electricity sources worldwide [S4][S6]."
            ),
        },
        {
            "source_id": "S5", "sub_question": sub_questions[1], "source_type": "web",
            "title": "Renewable Capacity Statistics 2024", "url_or_doc_id": "https://www.irena.org/publications/2024/renewable-capacity-statistics",
            "synthesis": (
                "Solar photovoltaic costs fell roughly 90% between 2010 and 2020 as "
                "manufacturing scaled globally, making utility-scale solar one of the "
                "cheapest sources of new electricity generation in much of the world by "
                "the early 2020s [S3]. Modern commercial panels convert 18-22% of "
                "incident sunlight to electricity, up from single-digit efficiencies in "
                "early spacecraft-era cells [S3]. Wind turbine capacity has similarly "
                "grown from tens of kilowatts in the 1980s to over 12-15 megawatts per "
                "offshore unit today, with wind now among the fastest-growing "
                "electricity sources worldwide [S4][S6]."
            ),
        },
        {
            "source_id": "S6", "sub_question": sub_questions[2], "source_type": "kb",
            "title": "Policy Drivers: Feed-in Tariffs and Tax Credits", "url_or_doc_id": "re-010",
            "synthesis": (
                "Government policy has strongly shaped adoption: Germany's 2000 "
                "Renewable Energy Sources Act pioneered feed-in tariffs that guaranteed "
                "producers a fixed above-market price, providing investment certainty "
                "that drove early European solar and wind deployment [S6]. In the "
                "United States, the Investment Tax Credit and Production Tax Credit have "
                "similarly offset capital costs since the 1990s/2000s, and renewable "
                "portfolio standards (minimum renewable-share mandates) are used "
                "worldwide as a third lever [S6]."
            ),
        },
        {
            "source_id": "S7", "sub_question": sub_questions[3], "source_type": "kb",
            "title": "Common Criticisms and Limitations", "url_or_doc_id": "re-012",
            "synthesis": (
                "The main limiting factors are intermittency (solar and wind output "
                "varies with weather, requiring grid flexibility or storage at high "
                "penetration), supply chains for manufacturing materials (silicon, rare "
                "earths, lithium, cobalt) with their own environmental and labor "
                "concerns, and local ecosystem or community impacts from large "
                "hydropower, wind, or solar installations [S7]. Longer-duration energy "
                "storage -- covering multi-day generation lulls -- remains an active area "
                "of technology development [S8]."
            ),
        },
        {
            "source_id": "S8", "sub_question": sub_questions[3], "source_type": "kb",
            "title": "Energy Storage and Grid Integration", "url_or_doc_id": "re-009",
            "synthesis": (
                "The main limiting factors are intermittency (solar and wind output "
                "varies with weather, requiring grid flexibility or storage at high "
                "penetration), supply chains for manufacturing materials (silicon, rare "
                "earths, lithium, cobalt) with their own environmental and labor "
                "concerns, and local ecosystem or community impacts from large "
                "hydropower, wind, or solar installations [S7]. Longer-duration energy "
                "storage -- covering multi-day generation lulls -- remains an active area "
                "of technology development [S8]."
            ),
        },
    ]

    draft = (
        "Renewable energy now supplies roughly 30% of global electricity generation, "
        "up from a small fraction in the 1990s, driven primarily by sharp cost "
        "declines in solar and wind and by sustained policy support. This report "
        "summarizes the main renewable categories, how their costs and deployment "
        "have evolved since the early 2000s, the policy mechanisms behind that "
        "growth, and the challenges that still constrain further adoption.\n\n"
        "## Findings\n\n"
        "### What are the primary categories of renewable energy and how does each generate electricity?\n\n"
        "Renewable energy is generated from naturally replenishing sources -- "
        "sunlight, wind, moving water, geothermal heat, and biomass -- that are not "
        "depleted on human timescales [S1]. The main categories are solar "
        "photovoltaics, wind turbines, hydropower, geothermal plants, and "
        "biomass/bioenergy conversion, each converting a different natural energy "
        "flow into electricity or fuel [S1][S2][S3][S4].\n\n"
        "### How has the cost of solar and wind power changed since the early 2000s?\n\n"
        "Solar photovoltaic costs fell roughly 90% between 2010 and 2020 as "
        "manufacturing scaled globally, making utility-scale solar one of the "
        "cheapest sources of new electricity generation in much of the world by the "
        "early 2020s [S3]. Modern commercial panels convert 18-22% of incident "
        "sunlight to electricity, up from single-digit efficiencies in early "
        "spacecraft-era cells [S3]. Wind turbine capacity has similarly grown from "
        "tens of kilowatts in the 1980s to over 12-15 megawatts per offshore unit "
        "today, with wind now among the fastest-growing electricity sources "
        "worldwide [S4][S5].\n\n"
        "### What policy mechanisms have driven renewable energy adoption globally?\n\n"
        "Government policy has strongly shaped adoption: Germany's 2000 Renewable "
        "Energy Sources Act pioneered feed-in tariffs that guaranteed producers a "
        "fixed above-market price, providing investment certainty that drove early "
        "European solar and wind deployment [S6]. In the United States, the "
        "Investment Tax Credit and Production Tax Credit have similarly offset "
        "capital costs since the 1990s/2000s, and renewable portfolio standards "
        "(minimum renewable-share mandates) are used worldwide as a third lever [S6].\n\n"
        "### What are the main challenges that still limit renewable energy adoption?\n\n"
        "The main limiting factors are intermittency (solar and wind output varies "
        "with weather, requiring grid flexibility or storage at high penetration), "
        "supply chains for manufacturing materials (silicon, rare earths, lithium, "
        "cobalt) with their own environmental and labor concerns, and local ecosystem "
        "or community impacts from large hydropower, wind, or solar installations "
        "[S7]. Longer-duration energy storage -- covering multi-day generation lulls -- "
        "remains an active area of technology development [S8].\n\n"
        "## Conclusion\n\n"
        "The last two decades saw renewable energy shift from a policy-subsidized "
        "niche to the cheapest source of new electricity generation in most markets, "
        "driven by steep cost declines in solar and wind and reinforced by feed-in "
        "tariffs, tax credits, and portfolio standards. The remaining barriers are "
        "increasingly about grid integration and storage rather than raw generation "
        "cost."
    )

    trace = [
        _trace(t0, "plan", 0.0, "Generated 4 sub-question(s)."),
        _trace(
            t0, "research", 0.9,
            "Categories -> 2 source(s) via kb; Cost trends -> 3 source(s) via kb+web; "
            "Policy -> 1 source(s) via kb; Challenges -> 2 source(s) via kb",
        ),
        _trace(t0, "draft", 1.6, "Drafted report (revision 1)."),
        _trace(
            t0, "critique", 2.1,
            "Decision=revise | The cost-trends section should explicitly mention a "
            "recent data point (e.g. 2023/2024 capacity figures), not just 2010-2020 "
            "trends.",
        ),
        _trace(
            t0, "research", 2.6,
            "Cost trends -> 1 source(s) via web (added IRENA 2024 capacity statistics)",
        ),
        _trace(t0, "draft", 3.3, "Drafted report (revision 2)."),
        _trace(t0, "critique", 3.8, "Decision=approve | Well-cited, directly answers all sub-questions."),
        _trace(t0, "human_review", 6.0, "Human decision=approve | Clear and well-sourced, ready to publish."),
        _trace(t0, "finalize", 6.1, "Run finalized with status=completed."),
    ]

    final_report = draft + (
        "\n\n---\n\n## Sources\n\n"
        "- **[S1]** Defining Renewable Energy (Knowledge Base: re-001)\n"
        "- **[S2]** Early History: Wind and Water Power (Knowledge Base: re-002)\n"
        "- **[S3]** Solar Photovoltaics: From Lab to Grid Scale (Knowledge Base: re-003)\n"
        "- **[S4]** Modern Wind Power (Knowledge Base: re-004)\n"
        "- **[S5]** Renewable Capacity Statistics 2024 (Web: https://www.irena.org/publications/2024/renewable-capacity-statistics)\n"
        "- **[S6]** Policy Drivers: Feed-in Tariffs and Tax Credits (Knowledge Base: re-010)\n"
        "- **[S7]** Common Criticisms and Limitations (Knowledge Base: re-012)\n"
        "- **[S8]** Energy Storage and Grid Integration (Knowledge Base: re-009)\n"
    )

    state_snapshot = {
        "question": question,
        "sub_questions": sub_questions,
        "findings": findings,
        "draft": draft,
        "draft_revision": 2,
        "critique_decision": "approve",
        "critique_feedback": "Well-cited, directly answers all sub-questions.",
        "revision_count": 1,
        "human_decision": "approve",
        "human_feedback": "Clear and well-sourced, ready to publish.",
        "human_revision_count": 0,
        "final_report": final_report,
        "status": "completed",
    }

    return Run(
        id=run_id,
        question=question,
        status="completed",
        final_report=final_report,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=6.1),
    )


def build_microservices_run() -> Run:
    run_id = str(uuid.uuid4())
    t0 = datetime.now(timezone.utc) - timedelta(hours=14)
    question = (
        "How do microservices architectures compare to monolithic architectures in "
        "terms of scalability, deployment complexity, and team organization?"
    )
    sub_questions = [
        "What are the key architectural differences between microservices and monolithic systems?",
        "How does each approach affect deployment complexity and CI/CD pipelines?",
        "What are the implications for team structure and ownership (Conway's Law)?",
        "What are common pitfalls when migrating from a monolith to microservices?",
    ]

    findings = [
        {
            "source_id": "S1", "sub_question": sub_questions[0], "source_type": "web",
            "title": "Microservices - Martin Fowler", "url_or_doc_id": "https://martinfowler.com/articles/microservices.html",
            "synthesis": (
                "A monolith deploys all functionality as a single unit sharing one "
                "process and typically one database, while microservices split an "
                "application into independently deployable services, each owning its "
                "own data store and communicating over the network (commonly HTTP/REST "
                "or messaging) [S1]. This independence is the source of both "
                "microservices' main benefits (independent scaling and deployment) and "
                "its main costs (network latency, distributed data consistency) [S1][S2]."
            ),
        },
        {
            "source_id": "S2", "sub_question": sub_questions[0], "source_type": "web",
            "title": "Monolith vs. Microservices - AWS Architecture Blog", "url_or_doc_id": "https://aws.amazon.com/blogs/architecture/monolith-vs-microservices/",
            "synthesis": (
                "A monolith deploys all functionality as a single unit sharing one "
                "process and typically one database, while microservices split an "
                "application into independently deployable services, each owning its "
                "own data store and communicating over the network (commonly HTTP/REST "
                "or messaging) [S1]. This independence is the source of both "
                "microservices' main benefits (independent scaling and deployment) and "
                "its main costs (network latency, distributed data consistency) [S1][S2]."
            ),
        },
        {
            "source_id": "S3", "sub_question": sub_questions[1], "source_type": "web",
            "title": "Microservices Trade-Offs - Martin Fowler", "url_or_doc_id": "https://martinfowler.com/articles/microservices.html#Trade-Offs",
            "synthesis": (
                "Monoliths generally have simpler CI/CD pipelines -- one build, one test "
                "suite, one deployable artifact -- but every change requires "
                "redeploying the whole application and testing the whole surface area "
                "[S3]. Microservices allow each service to be built, tested, and "
                "deployed independently, shrinking blast radius and enabling faster "
                "release cadence per team, at the cost of needing significant "
                "infrastructure investment: service discovery, per-service pipelines, "
                "distributed tracing, and container orchestration [S3][S4]."
            ),
        },
        {
            "source_id": "S4", "sub_question": sub_questions[1], "source_type": "web",
            "title": "Building Microservices, 2nd Edition - Sam Newman (O'Reilly)", "url_or_doc_id": "https://www.oreilly.com/library/view/building-microservices-2nd/9781492034018/",
            "synthesis": (
                "Monoliths generally have simpler CI/CD pipelines -- one build, one test "
                "suite, one deployable artifact -- but every change requires "
                "redeploying the whole application and testing the whole surface area "
                "[S3]. Microservices allow each service to be built, tested, and "
                "deployed independently, shrinking blast radius and enabling faster "
                "release cadence per team, at the cost of needing significant "
                "infrastructure investment: service discovery, per-service pipelines, "
                "distributed tracing, and container orchestration [S3][S4]."
            ),
        },
        {
            "source_id": "S5", "sub_question": sub_questions[2], "source_type": "web",
            "title": "How Do Committees Invent? (Conway's Law)", "url_or_doc_id": "http://www.melconway.com/Home/Committees_Paper.html",
            "synthesis": (
                "Conway's Law observes that a system's architecture tends to mirror the "
                "communication structure of the organization that builds it [S5]. In "
                "practice, microservices work best with small, autonomous teams that "
                "each own one or a few services end-to-end (the 'two-pizza team' "
                "model), whereas a monolith is naturally maintained by a single team or "
                "a set of teams that must coordinate closely on one shared codebase "
                "[S5][S6]."
            ),
        },
        {
            "source_id": "S6", "sub_question": sub_questions[2], "source_type": "web",
            "title": "Team Topologies - Skelton & Pais", "url_or_doc_id": "https://teamtopologies.com/",
            "synthesis": (
                "Conway's Law observes that a system's architecture tends to mirror the "
                "communication structure of the organization that builds it [S5]. In "
                "practice, microservices work best with small, autonomous teams that "
                "each own one or a few services end-to-end (the 'two-pizza team' "
                "model), whereas a monolith is naturally maintained by a single team or "
                "a set of teams that must coordinate closely on one shared codebase "
                "[S5][S6]."
            ),
        },
        {
            "source_id": "S7", "sub_question": sub_questions[3], "source_type": "web",
            "title": "MonolithFirst - Martin Fowler", "url_or_doc_id": "https://martinfowler.com/bliki/MonolithFirst.html",
            "synthesis": (
                "The most commonly cited pitfall is migrating to microservices before "
                "the domain boundaries are well understood, which tends to produce a "
                "'distributed monolith' -- many services that must still be deployed "
                "together because their boundaries don't match real business "
                "capabilities [S7]. Other frequent mistakes include underinvesting in "
                "observability (distributed tracing, centralized logging) before "
                "splitting services, and splitting too early in a product's life when "
                "the team is still small [S7]."
            ),
        },
    ]

    draft = (
        "Microservices and monolithic architectures make different trade-offs "
        "across scalability, deployment complexity, and team organization, and "
        "neither is universally 'better' -- the right choice depends on team size, "
        "domain maturity, and operational investment. This report compares the two "
        "approaches directly across those three dimensions and highlights the most "
        "common migration pitfalls.\n\n"
        "## Findings\n\n"
        "### What are the key architectural differences between microservices and monolithic systems?\n\n"
        "A monolith deploys all functionality as a single unit sharing one process "
        "and typically one database, while microservices split an application into "
        "independently deployable services, each owning its own data store and "
        "communicating over the network (commonly HTTP/REST or messaging) [S1]. This "
        "independence is the source of both microservices' main benefits "
        "(independent scaling and deployment) and its main costs (network latency, "
        "distributed data consistency) [S1][S2].\n\n"
        "### How does each approach affect deployment complexity and CI/CD pipelines?\n\n"
        "Monoliths generally have simpler CI/CD pipelines -- one build, one test "
        "suite, one deployable artifact -- but every change requires redeploying the "
        "whole application and testing the whole surface area [S3]. Microservices "
        "allow each service to be built, tested, and deployed independently, "
        "shrinking blast radius and enabling faster release cadence per team, at the "
        "cost of needing significant infrastructure investment: service discovery, "
        "per-service pipelines, distributed tracing, and container orchestration "
        "[S3][S4].\n\n"
        "### What are the implications for team structure and ownership (Conway's Law)?\n\n"
        "Conway's Law observes that a system's architecture tends to mirror the "
        "communication structure of the organization that builds it [S5]. In "
        "practice, microservices work best with small, autonomous teams that each "
        "own one or a few services end-to-end (the 'two-pizza team' model), whereas "
        "a monolith is naturally maintained by a single team or a set of teams that "
        "must coordinate closely on one shared codebase [S5][S6].\n\n"
        "### What are common pitfalls when migrating from a monolith to microservices?\n\n"
        "The most commonly cited pitfall is migrating to microservices before the "
        "domain boundaries are well understood, which tends to produce a "
        "'distributed monolith' -- many services that must still be deployed "
        "together because their boundaries don't match real business capabilities "
        "[S7]. Other frequent mistakes include underinvesting in observability "
        "(distributed tracing, centralized logging) before splitting services, and "
        "splitting too early in a product's life when the team is still small [S7].\n\n"
        "## Conclusion\n\n"
        "Microservices trade simplicity for independent scalability and deployment, "
        "and that trade only pays off once an organization has both the domain "
        "understanding to draw good service boundaries and the operational maturity "
        "(observability, per-service pipelines) to run many services well. Teams "
        "without both are frequently better served starting with a well-structured "
        "monolith."
    )

    trace = [
        _trace(t0, "plan", 0.0, "Generated 4 sub-question(s)."),
        _trace(
            t0, "research", 0.8,
            "Architectural differences -> 2 source(s) via web; Deployment complexity -> "
            "2 source(s) via web; Team structure -> 2 source(s) via web; Migration "
            "pitfalls -> 1 source(s) via web",
        ),
        _trace(t0, "draft", 1.5, "Drafted report (revision 1)."),
        _trace(t0, "critique", 2.0, "Decision=approve | Balanced, well-cited, and directly answers all four sub-questions."),
        _trace(t0, "human_review", 3.5, "Human decision=approve | Good balance, no changes needed."),
        _trace(t0, "finalize", 3.6, "Run finalized with status=completed."),
    ]

    final_report = draft + (
        "\n\n---\n\n## Sources\n\n"
        "- **[S1]** Microservices - Martin Fowler (Web: https://martinfowler.com/articles/microservices.html)\n"
        "- **[S2]** Monolith vs. Microservices - AWS Architecture Blog (Web: https://aws.amazon.com/blogs/architecture/monolith-vs-microservices/)\n"
        "- **[S3]** Microservices Trade-Offs - Martin Fowler (Web: https://martinfowler.com/articles/microservices.html#Trade-Offs)\n"
        "- **[S4]** Building Microservices, 2nd Edition - Sam Newman (Web: https://www.oreilly.com/library/view/building-microservices-2nd/9781492034018/)\n"
        "- **[S5]** How Do Committees Invent? (Conway's Law) (Web: http://www.melconway.com/Home/Committees_Paper.html)\n"
        "- **[S6]** Team Topologies - Skelton & Pais (Web: https://teamtopologies.com/)\n"
        "- **[S7]** MonolithFirst - Martin Fowler (Web: https://martinfowler.com/bliki/MonolithFirst.html)\n"
    )

    state_snapshot = {
        "question": question,
        "sub_questions": sub_questions,
        "findings": findings,
        "draft": draft,
        "draft_revision": 1,
        "critique_decision": "approve",
        "critique_feedback": "Balanced, well-cited, and directly answers all four sub-questions.",
        "revision_count": 0,
        "human_decision": "approve",
        "human_feedback": "Good balance, no changes needed.",
        "human_revision_count": 0,
        "final_report": final_report,
        "status": "completed",
    }

    return Run(
        id=run_id,
        question=question,
        status="completed",
        final_report=final_report,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=3.6),
    )


def seed() -> None:
    with SessionLocal() as db:
        for build in (build_renewable_energy_run, build_microservices_run):
            run = build()
            existing = db.get(Run, run.id)
            if existing is None:
                db.add(run)
        db.commit()
    print("Seeded example runs.")


if __name__ == "__main__":
    seed()
